package net.maizegenetics.webapp.yaml

import net.maizegenetics.webapp.model.FieldSpec
import net.maizegenetics.webapp.model.FieldType
import net.maizegenetics.webapp.model.PipelineSpec
import net.maizegenetics.webapp.state.AppState

/**
 * Serializes the builder [AppState] into an orchestrate-compatible YAML
 * document.
 *
 * Emission rules (matching what `Orchestrate.parseYamlConfig` expects):
 *  - `version` is always written as a quoted string.
 *  - `work_dir` is written (quoted) when non-blank.
 *  - `run_steps` lists the enabled steps in schema order.
 *  - Each enabled step becomes a top-level block. A field is written when it
 *    is required OR the user supplied a non-blank value. A step with no
 *    emitted fields is written as `step: {}` (the parser only checks the key
 *    is present, then applies its own defaults).
 *  - TEXT / ENUM values are quoted; INT / BOOL values are emitted bare.
 */
object YamlBuilder {

    fun build(spec: PipelineSpec, state: AppState): String {
        val sb = StringBuilder()
        sb.appendLine("# Generated by the seq_sim Orchestrate YAML Builder")
        sb.appendLine("# Review the values below, then run:")
        sb.appendLine("#   ./gradlew run --args=\"orchestrate --config <this-file>\"")
        sb.appendLine()
        sb.appendLine("version: ${quote(spec.version)}")
        if (state.workDir.isNotBlank()) {
            sb.appendLine("work_dir: ${quote(state.workDir)}")
        }
        sb.appendLine()

        val enabledSteps = spec.steps.filter { it.key in state.enabled }

        if (enabledSteps.isNotEmpty()) {
            sb.appendLine("run_steps:")
            enabledSteps.forEach { sb.appendLine("  - ${it.key}") }
            sb.appendLine()
        }

        for (step in enabledSteps) {
            val stepValues = state.values[step.key].orEmpty()
            val emitted = step.fields.mapNotNull { field ->
                val raw = stepValues[field.key]?.trim().orEmpty()
                if (field.required || raw.isNotEmpty()) {
                    "  ${field.key}: ${formatValue(field, raw)}"
                } else {
                    null
                }
            }
            if (emitted.isEmpty()) {
                sb.appendLine("${step.key}: {}")
            } else {
                sb.appendLine("${step.key}:")
                emitted.forEach { sb.appendLine(it) }
            }
            sb.appendLine()
        }

        return sb.toString().trimEnd() + "\n"
    }

    private fun formatValue(field: FieldSpec, raw: String): String = when (field.type) {
        FieldType.INT, FieldType.BOOL -> if (raw.isEmpty()) "\"\"" else raw
        FieldType.TEXT, FieldType.ENUM -> quote(raw)
    }

    private fun quote(value: String): String =
        "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
